<a href="https://colab.research.google.com/github/blessonpaul/machinelearning/blob/master/ml_0730_blessonpaul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/blessonpaul/machinelearning/master/wine-new.csv')
X = dataset.iloc[:, [0, 1]].values
y = dataset.iloc[:, 2].values

# Splitting the dataset into the Training set and Test set
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#-----------------------------------------------------------
# Documentation for sklearn.neighbors.KNeighborsClassifier:
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
# n_neighbors = # of neighbors 
# metric      = distance metric 
# p           = parameter for the Minkowski metric: 
# if p = 1:     use the manhattan_distance 
# if p = 2:     use the euclidean_distance 
#-----------------------------------------------------------

# ====> INSERT YOUR CLASSIFIER CODE HERE <====
# Fitting classifier to the Training set
# Create your classifier here
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state = 0)
classifier.fit(X_train, y_train) 
# ====> INSERT YOUR CLASSIFIER CODE HERE <====

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:")
print(cm)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))


confusion matrix:
[[11  1  2]
 [ 0 13  3]
 [ 0  1  5]]
0.8055555555555556


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/blessonpaul/machinelearning/master/wine-new.csv')
X = dataset.iloc[:, [0, 1]].values
y = dataset.iloc[:, 2].values

# Splitting the dataset into the Training set and Test set
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#-----------------------------------------------------------
# Documentation for sklearn.neighbors.KNeighborsClassifier:
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
# n_neighbors = # of neighbors 
# metric      = distance metric 
# p           = parameter for the Minkowski metric: 
# if p = 1:     use the manhattan_distance 
# if p = 2:     use the euclidean_distance 
#-----------------------------------------------------------

# ====> INSERT YOUR CLASSIFIER CODE HERE <====
# Fitting classifier to the Training set
# Create your classifier here
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 3, criterion='entropy', random_state = 0)
classifier.fit(X_train, y_train)
# ====> INSERT YOUR CLASSIFIER CODE HERE <====

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:")
print(cm)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))


confusion matrix:
[[11  1  2]
 [ 0 13  3]
 [ 1  1  4]]
0.7777777777777778


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/blessonpaul/machinelearning/master/wine-new.csv')
X = dataset.iloc[:, [0, 1]].values
y = dataset.iloc[:, 2].values

# Splitting the dataset into the Training set and Test set
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#-----------------------------------------------------------
# Documentation for sklearn.neighbors.KNeighborsClassifier:
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
# n_neighbors = # of neighbors 
# metric      = distance metric 
# p           = parameter for the Minkowski metric: 
# if p = 1:     use the manhattan_distance 
# if p = 2:     use the euclidean_distance 
#-----------------------------------------------------------

# ====> INSERT YOUR CLASSIFIER CODE HERE <====
# Fitting classifier to the Training set
# Create your classifier here
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion='entropy', random_state = 0)
classifier.fit(X_train, y_train)
# ====> INSERT YOUR CLASSIFIER CODE HERE <====

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:")
print(cm)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

confusion matrix:
[[13  0  1]
 [ 0 15  1]
 [ 0  1  5]]
0.9166666666666666


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/blessonpaul/machinelearning/master/wine-new.csv')
X = dataset.iloc[:, [0, 1]].values
y = dataset.iloc[:, 2].values

# Splitting the dataset into the Training set and Test set
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#-----------------------------------------------------------
# Documentation for sklearn.neighbors.KNeighborsClassifier:
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
# n_neighbors = # of neighbors 
# metric      = distance metric 
# p           = parameter for the Minkowski metric: 
# if p = 1:     use the manhattan_distance 
# if p = 2:     use the euclidean_distance 
#-----------------------------------------------------------

# ====> INSERT YOUR CLASSIFIER CODE HERE <====
# Fitting classifier to the Training set
# Create your classifier here
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 20, criterion='entropy', random_state = 0)
classifier.fit(X_train, y_train)
# ====> INSERT YOUR CLASSIFIER CODE HERE <====

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:")
print(cm)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

confusion matrix:
[[13  0  1]
 [ 0 15  1]
 [ 0  1  5]]
0.9166666666666666
